name: Continuous Integration
on: 
  push:
  pull_request:

jobs:
  format_checking:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.11'
      - name: Dependancies installation
        run: |
          python -m pip install --upgrade pip 
          pip install mypy
      - name: Mypy type checking
        run: | 
          PYTHONPATH=src mypy src/data_parser/